"""Add is_verified column

Revision ID: a20ebb6dedd3
Revises: c362e86cf413
Create Date: 2024-03-31 17:46:42.185089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a20ebb6dedd3'
down_revision = 'c362e86cf413'
branch_labels = None
depends_on = None


# def upgrade():
#     # ### commands auto generated by Alembic - please adjust! ###
#     with op.batch_alter_table('users', schema=None) as batch_op:
#         batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=False))

#     # ### end Alembic commands ###

def upgrade():
    op.drop_table('users')
    op.create_table(
        'users',
        sa.Column('id', sa.String(), primary_key=True),
        sa.Column('email', sa.String(), unique=True, nullable=False),
        sa.Column('password', sa.String(), nullable=False),
        sa.Column('created_on', sa.DateTime(), nullable=False),
        sa.Column('is_admin', sa.Boolean(), nullable=False, default=False),
        sa.Column('is_verified', sa.Boolean(), nullable=False, server_default='false')  # New column
    )



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_verified')

    # ### end Alembic commands ###
